version: 2.0

orbs:
    hello: circleci/creditreport@0.1.0

jobs:
  build:
    working_directory: ~/creditreport # directory where steps will run
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: 'just check lint'
          command: './node_modules/.bin/eslint src/**/*.{vue,js}'
