version: 2.0

orbs:
    hello: circleci/creditreport@0.1.0

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: 'NPM update'
          command: 'sudo npm install -g npm@latest'
      - run:
          name: 'install node modules'
          command: npm install
      - run:
          name: 'just check lint'
          command: './node_modules/.bin/eslint src/**/*.{vue,js}'
