version: 2.0

orbs:
    hello: circleci/creditreport@0.1.0

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo 'export PATH=$PATH:$CIRCLE_PROJECT_REPONAME/node_modules/.bin' >> $BASH_ENV
      - run: echo $BASH_ENV
      - run: cat $BASH_ENV
      - run: cat $CIRCLE_PROJECT_REPONAME
      - run: eslint src/**/*.{vue,js}